source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!


target 'BeautifulTextField_Example' do
  
  pod 'BeautifulTextField', :path => '../'
  
  target 'BeautifulTextField_Tests' do
    
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
    # pod 'FBSnapshotTestCase'
    # pod 'Nimble-Snapshots'
    
  end
  
end
