use_frameworks!

target 'BeautifulTextField_Example' do
  pod 'BeautifulTextField', :path => '../'

  target 'BeautifulTextField_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
